### PR TITLE
Password errors were not being thrown

### PR DESCRIPTION
**Pull request by hbinded**
I noticed that password errors were not being thrown if the password was not the correct. This is because  on line 353, the error being thrown is <pre>$this->error($this->CI->lang->line('aauth_error_login_failed'));</pre> but in the <pre>application/language/english/aauth_lang.php</pre> the line is missing. My personal fix was to add a line in the <pre>aauth_lang.php</pre> file in accordance to what was already there. 

To Mr. Emre: I don't want to re-invent the wheel here. You can reject this if it doesn't sound sensible. I'm just trying to help

p.s. I'm always using CI3.

### CODE REVIEW

**Comment by emreakay** [comment]
Thank you very much @hbinded for your contribition. :+1: 
Also thanks for special note for me :)

**Comment by emreakay** [comment]
merged

**Comment by hbinded** [comment]
Thank you kind sir! Love your auth library just fyi

**Comment by emreakay** [comment]
i am thankfull as well. waiting other contribitions from you :+1:

**Pull request merged**
