### PR TITLE
Google signin

### PR DESCRIPTION
**Pull request by scombat**
![Image of Yaktocat]
(http://icons.iconarchive.com/icons/graphicloads/100-flat/64/warning-icon.png)

Please, be careful using this feature.
The refresh token isn't tested...

How to use this :
> Composer install

```php
        public function google()
        {
                if ( ($url = $this->aauth->google_connect()) )
                       echo $url; // Contain the url for the google btn
        }

        public function redirect_uri()
       {
             // If user exists : login
             // Else, create the user and if email is google verified
             // login user overwize send a validation mail
             $this->aauth->google_connect();
       }
```

### CODE REVIEW

**Comment by emreakay** [comment]
can you solve the confilicts?

**Comment by scombat** [comment]
It's done.

**Comment by emreakay** [comment]
Has anybody tasted this function?

**Comment by REJack** [comment]
nope

**Comment by scombat** [comment]
First : I think, it's necessary to implement this feature, and similar others, into a global scope for Third party auth functionality in a next milestone for keeping a unique paradigme in our code.

Second : With the differences betweens other auth methods it seems, for me, to be important to determine a list of targeted third party. (Google, Facebook, Twitter, Github etc...) And set a lot of unit testing procedure for each.

**Comment by REJack** [comment]
@scomat First & Second: i think the same. i work on an overhauled version of Aauth (v3)  in addition to my company work and this is a task on my todo list for a long time :smile:

**Comment by REJack** [comment]
i close this PR, i add social sign-in(google, github, facebook etc) in the next release (v3.0.0)

**Pull request closed without merging**
