### PR TITLE
TOTP and some improvements

### PR DESCRIPTION
**Pull request by REJack**
added Time-Based One-Time Password
- ``totp_active`` added to config vars
- ``totp_only_on_ip_change`` added to config vars
- ``totp_reset_over_reset_password`` added to config vars

added configuration to not use cookies if sessions are enabled.
- ``use_cookies`` added to config vars

changed some default config vars to increase the security
- ``no_permission`` to FALSE
- ``max`` to 24
- ``valid_chars`` to empty array

### CODE REVIEW

**Comment by ManeBit** [comment]
### Looks good!

##### We really should consider writing some unit tests for all the Aauth functions. It will be really helpful to keep things from getting convoluted.  

I'd recommend the following CI instance as a starting point for writing these tests.
https://github.com/kenjis/ci-phpunit-test
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md

**Comment by REJack** [comment]
good idea i'll gone start write some tests at weekend, first we need the DB seeds :smile:

**Comment by REJack** [comment]
i'll add my first release of my unit test for Aauth
https://github.com/REJack/CodeIgniter-Aauth/tree/unit_tests

without features that use cookies/session or sends email

**Comment by emreakay** [comment]
hi @REJack i am sorry but i cannot merge your commit because i first merged @ManeBit 's commits so there is a conflict in your commits. Please can you now open new pull request after solve conficts? 

thank you for your understanding

**Comment by REJack** [comment]
Yeah i solve the conflicts then i create a new PR in the next days

**Comment by emreakay** [comment]
Ok I am waiting

**Comment by REJack** [comment]
now i solved the conflict

**Comment by ManeBit** [comment]
That's very odd that the password length would cause a conflict ¯\_(ツ)_/¯

**Comment by emreakay** [comment]
done

**Comment by REJack** [comment]
thx :+1:

**Comment by REJack** [comment]
would you create a new release?

**Comment by emreakay** [comment]
i have already created :+1:

**Comment by REJack** [comment]
perfect thx :+1:

**Pull request merged**
