### PR TITLE
Info and Errors (and other bug fixes)

### PR DESCRIPTION
**Pull request by tswagger**
I have addressed a few issues/bugs with the core functionality (mostly surrounding the info and errors) as well as added a few minor features.  Below is a list of changes:

- Added flashdata boolean to error() and info() allowing the option for errors/messages to only remain for current page.
- Added clear_errors() and clear_infos() which removes all errors and infos from Aauth storage as well as flashdata storage
- Loaded flashdata into errors and infos on construct in order to fully utilize flashdata (as a result, keep_errors() and keep_infos() now work properly)
- Added boolean return value to login_fast()
- Remove redundant indexes from Aauth_v2.sql
- Removed bool return value from get_errors_array() and get_infos_array().  As "array" is in the method name, should only return array.  Change should remain backwards compatible as empty array will still evaluate to "false".
- Fix bug in which "is_allowed" returns true if user is logged in and has access to perm_id=1 and perm is non-existant.
- Modified list_user_var_keys() to return an array so that it can be looped through
- Fixed duplicate message when sending password reset email, line 424
- Modified lang-file constants to include prefix.  This will help avoid collisions. Also added a few missing items to the lang-file
- Updated SQL file to be a bit more efficient.
- Modified keep_infos() and keep_errors() to include non-flash data values on optional boolean parameter.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
:+1: This is nice work. I especially like the switch to Lord of the Rings in the example.

**Comment by REJack** [comment]
great work :+1:

**Comment by tswagger** [comment]
Thank you.

**Comment by emreakay** [comment]
Hey you are really fantastic bro.  :).

i love that .

Especially lord of ringa part :)
 
im going to commit this. But before i commit it i have to test it. But i dont have time to test.

Have you test this.?

**Comment by tswagger** [comment]
Emre -

I have tested it, as I am using a copy of it in a couple of my projects (most of my changes are issues I ran into on those projects).  But... please do test it on your end to make sure it meets your standards. :-)

**Comment by emreakay** [comment]
merged :+1: 

thank you again @tswagger for your contribition

**Pull request merged**
