### PR TITLE
Updated aauth.php

### PR DESCRIPTION
**Pull request by REJack**
changed use_cookies to true to provide CI2 Support

### CODE REVIEW

**Comment by REJack** [comment]
@emreakay with this PR you can close #58 & #61

**Comment by emreakay** [comment]
@REJack you are awesome.

**Comment by REJack** [comment]
@emreakay do you have skype or so? i have some questions for some further updates.

**Comment by emreakay** [comment]
i dont have skype. you can email me. emreakayfb@hotmail.com

**Comment by REJack** [comment]
@emreakay mail is out :+1:

**Comment by emreakay** [comment]
@REJack i didn't get any mail. i think something is wrong

**Comment by REJack** [comment]
@emreakay i sent it again with a different account.

**Pull request merged**
