### PR TITLE
some fixes and db_profile added

### LINKED ISSUE #34: db_prefix enhancement
I love your auth library.
I need some enhancement And i did it for me. I can not publish at the moment. But you can. 

At the moment you need to change your default db connection profile prefix to aauth for your library. 
But in fact it could be added on config variable as 'db_profile' and you can add Aauth library class a new variable aauth_db and if you call database connection after config variable and like this.
config > aauth.php
```
$config['aauth'] = array(
	'db_profile' => 'aauth', // aauth library use different dp_profile
```

add new public variable to Library class
libraries > Aauth.php 
```
/**
     * The CodeIgniter object variable
     * @var object
     */
    public $aauth_db;
```
in constructor of libraries > Aauth.php  call new db
```
         $this->CI->config->load('aauth');
         $this->config_vars = $this->CI->config->item('aauth');
        
         $this->aauth_db = $this->CI->load->database($this->config_vars['db_profile'],TRUE); 
```
and replace all "CI->db" with  "aauth_db"  in libraries > Aauth.php 

and in database configuration you can add new database configuration profile 
config > database.php
```
$db['aauth']['hostname'] = 'localhost';
$db['aauth']['username'] = 'username';
$db['aauth']['password'] = 'password';
$db['aauth']['database'] = 'username';
$db['aauth']['dbdriver'] = 'mysqli';
$db['aauth']['dbprefix'] = 'aauth_';
$db['aauth']['pconnect'] = TRUE;
```

### PR DESCRIPTION
**Pull request by REJack**
- added configurable login over name or email
- cleaned the config file (a lil prestep for a better documentation)
- added db profile (would close #34)
- removed 2 unused functions (user_exsist_by_name, user_exsist_by_id)
- fixed cookie creation for reCAPTCHA if it's not active
- changed the copyright info to this year
- configurable login over name or email by suggestion from @tswagger 
- added create_group and update_group $definiton from @tswagger SQL changes
- changed list_user_var_keys's output from array to object (similar to list_system_var_keys)
- fixed set_system_var bug (issue #39)
- added config var for reset_password_link and verification_link
- added checks from create_user in update_user 
 - user_exsist_by_email, valid_email
 - min-max pass length
 - user_exsist_by_name, valid_chars

### CODE REVIEW

**Comment by tswagger** [comment]
Looks great.

**Comment by REJack** [comment]
thats a good idea, i will change it too

**Comment by REJack** [comment]
like that? :smile:

**Comment by tswagger** [comment]
Yeah, That looks better.  Gives the developer an option based on their preference or environment.

**Comment by tswagger** [comment]
Nice catch on the create_group and update_group!

**Comment by tswagger** [comment]
Raphael -

I created an account on your git server, but was not able to find the documentation.  If you are using "Read the Docs" to build the documentation I would propose following the format that CodeIgniter uses in their documentation.  Would love to help contribute on that if I can.

I started updating the Error and Info page (am not completely done), but you can see the current state on the wiki on my Aauth fork.

**Comment by REJack** [comment]
The project on my git is 'CodeIgniter-Aauth-Wiki' it contains only the docs.

i've added you to the project for write access, the documentation is located in the 'docs' folder.
If you push a commit it build a new version online.

At the moment i have only pushed the Method References based on the original docs. You can create the Error and Info page as you wish.

**Comment by REJack** [comment]
PR updated :smile:

**Comment by emreakay** [comment]
as Aauth community we are thankfull to you @REJack and @tswagger 

thank you for your contibition

**Comment by REJack** [comment]
thx for merge
i will add in the next days a new PR for TOTP :smile:

**Pull request merged**
