### PR TITLE
Urgent fixes for #47, #46 and Improvements

### PR DESCRIPTION
**Pull request by ManeBit**
### Bug fixes
* #47 Typos in function names. (user_exist functions)
* #46 Variable scope error. (within the update_user() function)

## Other Improvements
*  remind_password() now returns true and false. (true if email sent) (false if the email address doesn't exist in the DB).

> I highly recommend merging this branch in order to retain elegance and symmetry within the Aauth library.

### CODE REVIEW

**Comment by REJack** [comment]
nice work

**Comment by ManeBit** [comment]
Thanks! The docs should be updated too.

http://codeigniter-aauth-test.readthedocs.org/en/latest/functions/users.html#user_exsist_by_name

**Comment by emreakay** [comment]
Tank you very much for your contribution. 

As I have find time I will check and merge it. 

Probably this night I can. 

Sorry for latency

**Comment by REJack** [comment]
i change the docs this night

**Comment by ManeBit** [comment]
This also needs an update: http://codeigniter-aauth-test.readthedocs.org/en/latest/functions/users.html?highlight=remind_password#remind_password

**Comment by REJack** [comment]
i've updated remind_password in the docs

**Comment by ManeBit** [comment]
still waiting on the pr before moving on to further improvements...

**Comment by REJack** [comment]
me too :smile: my TOTP PR is almost finish

**Comment by emreakay** [comment]
I am so sorry guys 

I am too busy. I will merge them in 2 days.

**Comment by REJack** [comment]
i've added my TOTP PR

@ManeBit you can take a look over it

**Comment by ManeBit** [comment]
@emreakay I know you are busy, but I am willing to become a verified collaborator for Aauth. If you have time to talk on skype, we can discuss further.

A lot of us really depend on Aauth and I want to help further its development at a much faster pace. Thanks!

**Comment by emreakay** [comment]
I'm very pleased to hear that. 

My email is Emreakayfb@hotmail. Com I wanted to discuss about future of aauth deeply.

**Comment by antonPaluhin** [comment]
Guys, please fix update_user()!

**Comment by ManeBit** [comment]
@antonPaluhin You can clone from https://github.com/ManeBit/CodeIgniter-Aauth if urgent.

**Comment by emreakay** [comment]
merged :)

**Pull request merged**
